[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.com/"